/*#include <iostream>
using namespace std;

int main(){
    string letters[3][4] = {
        {"A","B","C","D" "\n"},
        {"E","F","G","H" "\n"},
        {"I","J","K","L" "\n"}
    };
    cout << letters[2][3];
    string Array[2][4] = {
    { "A", "B", "C", "D" "\n"},
    { "E", "F", "G", "H" "\n"}
    };
    cout << Array[0][2] << endl;
    string array[2][4] = {
    { "A", "B", "C", "D" "\n"},
    { "E", "F", "G", "H" "\n"}
    };
    array[0][0] = "Z" "\n";
    cout << array[0][0];

    int myNum[2][2]{
        {1,2},
        {3,4}
    };
    cout << myNum[1][1] << endl;
}*/

#include <iostream>
using namespace std;

int main(){
    int array[3][4] = {
        {2,3,4,5},
        {4,3,5,6}
    };
    cout << array[1][4];
}